
[[language]]
name = "python"
formatter = { command = "black", args = ["--quiet", "-l", "100", "-"] }
language-servers = ["pylsp"]


[[language]]
name = "c"
auto-format = true
formatter = { command  = "clang-format"}

[[language]]
name = "cpp"
auto-format = true
formatter = { command  = "clang-format"}
