[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]
config = {} # buggy behaviour, you need a pyproject.toml and pyrightconfig.json

[[language]]
name = "python"
formatter = { command = "black", args = ["--quiet", "-"] }
auto-format = true
language-servers = [ "pyright" ]


[[language]]
name = "c"
auto-format = true
formatter = { command  = "clang-format"}

[[language]]
name = "cpp"
auto-format = true
formatter = { command  = "clang-format"}
